/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "wall.pb-c.h"
void   wall__init
                     (Wall         *message)
{
  static Wall init_value = WALL__INIT;
  *message = init_value;
}
size_t wall__get_packed_size
                     (const Wall *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wall__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wall__pack
                     (const Wall *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wall__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wall__pack_to_buffer
                     (const Wall *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wall__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wall *
       wall__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wall *)
     protobuf_c_message_unpack (&wall__descriptor,
                                allocator, len, data);
}
void   wall__free_unpacked
                     (Wall *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wall__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   extension__init
                     (Extension         *message)
{
  static Extension init_value = EXTENSION__INIT;
  *message = init_value;
}
size_t extension__get_packed_size
                     (const Extension *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &extension__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t extension__pack
                     (const Extension *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &extension__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t extension__pack_to_buffer
                     (const Extension *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &extension__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Extension *
       extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Extension *)
     protobuf_c_message_unpack (&extension__descriptor,
                                allocator, len, data);
}
void   extension__free_unpacked
                     (Extension *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &extension__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vertex__init
                     (Vertex         *message)
{
  static Vertex init_value = VERTEX__INIT;
  *message = init_value;
}
size_t vertex__get_packed_size
                     (const Vertex *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &vertex__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vertex__pack
                     (const Vertex *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &vertex__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vertex__pack_to_buffer
                     (const Vertex *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &vertex__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vertex *
       vertex__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vertex *)
     protobuf_c_message_unpack (&vertex__descriptor,
                                allocator, len, data);
}
void   vertex__free_unpacked
                     (Vertex *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &vertex__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor wall__field_descriptors[9] =
{
  {
    "health",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(Wall, has_health),
    PROTOBUF_C_OFFSETOF(Wall, health),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exists",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Wall, has_exists),
    PROTOBUF_C_OFFSETOF(Wall, exists),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "solid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Wall, has_solid),
    PROTOBUF_C_OFFSETOF(Wall, solid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hot",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Wall, has_hot),
    PROTOBUF_C_OFFSETOF(Wall, hot),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(Wall, has_w),
    PROTOBUF_C_OFFSETOF(Wall, w),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(Wall, has_h),
    PROTOBUF_C_OFFSETOF(Wall, h),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(Wall, has_d),
    PROTOBUF_C_OFFSETOF(Wall, d),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wall, ext),
    &extension__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sprite_name",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wall, sprite_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wall__field_indices_by_name[] = {
  6,   /* field[6] = d */
  1,   /* field[1] = exists */
  7,   /* field[7] = ext */
  5,   /* field[5] = h */
  0,   /* field[0] = health */
  3,   /* field[3] = hot */
  2,   /* field[2] = solid */
  8,   /* field[8] = sprite_name */
  4,   /* field[4] = w */
};
static const ProtobufCIntRange wall__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor wall__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Wall",
  "Wall",
  "Wall",
  "",
  sizeof(Wall),
  9,
  wall__field_descriptors,
  wall__field_indices_by_name,
  1,  wall__number_ranges,
  (ProtobufCMessageInit) wall__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor extension__field_descriptors[2] =
{
  {
    "nverts",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Extension, has_nverts),
    PROTOBUF_C_OFFSETOF(Extension, nverts),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vert",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Extension, n_vert),
    PROTOBUF_C_OFFSETOF(Extension, vert),
    &vertex__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned extension__field_indices_by_name[] = {
  0,   /* field[0] = nverts */
  1,   /* field[1] = vert */
};
static const ProtobufCIntRange extension__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor extension__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Extension",
  "Extension",
  "Extension",
  "",
  sizeof(Extension),
  2,
  extension__field_descriptors,
  extension__field_indices_by_name,
  1,  extension__number_ranges,
  (ProtobufCMessageInit) extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vertex__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(Vertex, has_x),
    PROTOBUF_C_OFFSETOF(Vertex, x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(Vertex, has_y),
    PROTOBUF_C_OFFSETOF(Vertex, y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vertex__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange vertex__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vertex__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Vertex",
  "Vertex",
  "Vertex",
  "",
  sizeof(Vertex),
  2,
  vertex__field_descriptors,
  vertex__field_indices_by_name,
  1,  vertex__number_ranges,
  (ProtobufCMessageInit) vertex__init,
  NULL,NULL,NULL    /* reserved[123] */
};
